# devel.conf for kitty

launch --title "zsh" sh -c "fastfetch; zsh"

# Set the working directory for windows in the current tab
new_tab projects
launch --cwd="~/Projects/"

# Create the "code" window and run an editor in it to edit the project files
new_tab code
launch --hold zsh -c "source ~/.zshrc; cd ~/Projects/; nvim"

# Create a side window to run a shell to build or test project
new_tab run
launch --cwd="~/Projects/"
# Create another side window to keep an eye on some useful log file
new_tab monitor
launch btop
